### ISSUE TITLE
test my model trained on Things dataset where there are more than 1000 categories with modelvshuman benchmark

### ISSUE THREAD

**Issue by guomanshan** [bethgelab/model-vs-human#16]
My model is trained on Things dataset which includes more than 1000 categories. Can I test my model on this benchmark?

**Comment by rgeirhos** [comment]
Hi @guomanshan, thanks for your interest! 

If you can find a mapping from (a subset of) Things categories to the 16 classes* used in this benchmark, this should be possible by adapting https://github.com/bethgelab/model-vs-human/blob/master/modelvshuman/helper/human_categories.py where ImageNet categories are mapped to the 16 classes used in the model-vs-human benchmark. If this is not possible, then the benchmark can't be used and you could instead e.g. corrupt Things images with a package like this one https://github.com/bethgelab/imagecorruptions. Let me know if you have any questions.

*16 classes = ["knife", "keyboard", "elephant", "bicycle", "airplane", "clock", "oven", "chair", "bear", "boat", "cat", "bottle", "truck", "car", "bird", "dog"]
