### ISSUE TITLE
Request for data to reproduce figures

### ISSUE THREAD

**Issue by vihari** [bethgelab/model-vs-human#19]
Very interesting work and thanks very much for releasing it publicly. We are working on extending some of your results/studies, could you please provide more information related to Figure 2?

Figure 2 compares several models, but they are not all labeled. I am interested in finding out the accuracy-distortion tradeoff for each model. The figure shows this information at a coarse level, such as to compare all self-supervised models, adversarially trained models, etc. Would be perfect if you could provide the model-name (corresponding to your model zoo) and its corresponding performance at various distortion levels for the 12 distortion types that are considered. 

Thanks again, looking forward to hearing from you!

**Comment by rgeirhos** [comment]
Thanks for your interest! The model names (corresponding to the models in the model zoo) are listed here:
https://github.com/bethgelab/model-vs-human/blob/master/examples/plotting_definition.py#L45
You will be able to obtain the raw data by evaluating those models, which should enable you to aggregate the data in any way you like.

**Comment by vihari** [comment]
Perfect! This is what I am looking for, thanks a lot for your response.
