### ISSUE TITLE
Question Regarding Human Raw Dataset

### ISSUE THREAD

**Issue by jiyounglee-0523** [bethgelab/model-vs-human#20]
Hi! Thank you for providing a valuable dataset. 

As I dig into the raw data which contains human annotations, some questions raised in my mind. 
Below is how I analyzed the raw dataset in contrast experiment 

For an image named `0580_cop_dnn_c05_bicycle_10_n03792782_10129.png`, I extracted rows in which `image_id` matches 'c05_bicycle_10_n03792782_10129.png'.
Then, I got the following 4 rows. Here, `human_annotation` is a simple concatenation of all csv files in contrast experiment.
![image](https://user-images.githubusercontent.com/64568339/191685466-85b7547d-c8e0-43ee-b521-31577b6cf6cf.png)

Below is the visualization of image `0580_cop_dnn_c05_bicycle_10_n03792782_10129.png` 
![image](https://user-images.githubusercontent.com/64568339/191738291-d321d96d-a443-4c07-9390-895a71d61a39.png)

Although the image is not very clear, I do not fully agree with the human predictions. (They predicted 'clock', 'oven', 'bear', 'keyboard' -- It is very clear that the figure is not a keyboard.)
Is there anything wrong or I missed in the analysis? 

Thanks,

**Comment by rgeirhos** [comment]
Thanks for your question. Human classification performance at 5% contrast levels is at about 13% (judging from Figure 2f in https://openreview.net/pdf?id=QkljT4mrfs). Hence, errors are normal. Potential explanations for this particular image:
- you may not be viewing the image on a calibrated monitor as our participants did in the lab
- you may not be viewing the image for 200ms only, followed by a high-contrast 1/f noise mask as our participants did in the lab
Does this answer your question?
