### ISSUE TITLE
Question about shape bias

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [bethgelab/model-vs-human#21]
Could you please provide the formula to get the shape bias? Currently, I can successfully run this repo with my own model, but I am confused about how the shape bias is abtained. I will be very gratefully if you can elaborate it. Thanks!

**Comment by rgeirhos** [comment]
Thanks for your interest! Please have a look here: https://github.com/rgeirhos/texture-vs-shape#how-do-i-compute-the-shape-bias-of-a-model and let me know if you have any questions.
