### ISSUE TITLE
dataset path?

### ISSUE THREAD

**Issue by ahnchive** [bethgelab/model-vs-human#22]
Hi --- first thank you a lot for this useful dataset and API!

I'm trying to load the datasets using the following code, but got an error msg saying `dataset sketch path not found: model-vs-human/datasets/sketch/dnn/`

Does this mean that I should download the sketch image dataset myself from the original source and put under this path? Little more documentation on how the image dataset should be structured will be very useful! 
```
from modelvshuman.datasets import sketch,      
dataset = sketch(batch_size=16, num_workers=4)
```
Thank you!

**Comment by ahnchive** [comment]
Oh sorry never mind! I went straight to load dataset before run_evaluation, and missed the util function automatically load all necessary datasets. I will close this comment

**Comment by rgeirhos** [comment]
No worries, glad you were able to figure it out! Let me know in case we should update the description in the README to make this more clear.
