### ISSUE TITLE
Unable to load adversarially trained models

### ISSUE THREAD

**Issue by ajaysub110** [bethgelab/model-vs-human#24]
Hi

I'm unable to load any of the adversarially trained models `resnet50_l2_eps*`. I was able to until 2 months ago, but it seems like the repository: https://github.com/microsoft/robust-models-transfer no longer exists. Is there a workaround for this?

Thanks
Ajay

**Comment by rgeirhos** [comment]
Hi Ajay, thanks for reporting this, that's unfortunate! Doesn't look like we can fix this on our end; perhaps it may be possible to contact the authors of the dependency repo (from https://proceedings.neurips.cc/paper/2020/file/24357dd085d2c4b1a88a7e0692e60294-Paper.pdf)?

**Comment by rgeirhos** [comment]
Hi @ajaysub110, turns out that the robust models are available via Huggingface. This PR (https://github.com/bethgelab/model-vs-human/pull/25) should fix things - let me know if you run into any issues. Kudos to @thoklei for discovering this and the PR!

**Comment by ajaysub110** [comment]
Ah, great! Thank you for the fix @thoklei
