### ISSUE TITLE
dataset "original"

### ISSUE THREAD

**Issue by KogniJannis** [bethgelab/model-vs-human#26]
from what I can see most distortions include undistorted images in their evaluation so that the automatically generated plots work without a seperate scoring run on the original dataset. Is there any analysis for which I need to specifically obtain the "original" dataset?

**Comment by KogniJannis** [comment]
thanks, that helped. So "original" is more of a legacy identifier?

**Comment by rgeirhos** [comment]
Ah gotcha - the 'original' dataset is a non-public dataset containing the base images from which I created the style transfer, silhouette and edge images.
