### ISSUE TITLE
Cannot find some advanced model in the models.list_models("pytorch")

### ISSUE THREAD

**Issue by caiyancheng** [bethgelab/model-vs-human#29]
Thanks for your code? Have you add the [ViT-22B-384](https://arxiv.org/abs/2302.05442) in the pytorch model zoo? I haven't found it.

**Comment by rgeirhos** [comment]
Hi @caiyancheng thanks for your interest. The ViT-22B model checkpoints have not been made publicly available by the model authors, thus they are not part of the model zoo.

**Comment by OnlyForWW** [comment]
@caiyancheng Can you reproduce the example provided by the author?
