### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by OnlyForWW** [bethgelab/model-vs-human#30]
I followed the guidelines in the README and ran evaluate.py in the example; But an error occurred, indicating that the model could not be found: bagnet33 and simclr_resnet50x1; When I commented out these two models in evaluate.py, after running them, only the latex report did not generate a PDF, and there were only two benchmarked, table, and accuracy. tex in the assert; benchmark_table_humanlike.tex

The environment I am using is PyTorch 1.11.0; Ubuntu 20.04.

We urgently need your help.

**Comment by rgeirhos** [comment]
Hi @OnlyForWW, sorry to hear about your troubles. Could you post the entire stack trace of the error here for further context?

**Comment by rgeirhos** [comment]
Also - did the error occur during run_evaluation() or run_plotting() here? https://github.com/bethgelab/model-vs-human/blob/master/examples/evaluate.py#L30 (Can be checked by commenting out run_plotting() to see whether that already produces an error)

**Comment by OnlyForWW** [comment]
I'm running it with no errors reported other than the message that it's not looking for bagnet33 and simclr_resnet50x1. I checked that the generated image is also complete; however, in the letx-report directory, the full report is not generated. @rgeirhos

**Comment by OnlyForWW** [comment]
I've also tried commenting out the line of code you mentioned, but my machine doesn't report an error either.

**Comment by rgeirhos** [comment]
Can you post the full strack trace please?

**Comment by OnlyForWW** [comment]
I will try to fix this myself in the near future. When I solve the problem, I will document my solution in detail under this issue. Thank you for your kind reply.

**Comment by rgeirhos** [comment]
Happy to help get this fixed (just need more information).
