### ISSUE TITLE
not able to reproduce the results

### ISSUE THREAD

**Issue by happyhackingit** [bethgelab/model-vs-human#5]
Firstly thanks for sharing the interesting paper and code!

I followed the installation steps but running `python examples/evaluate.py` (didn't edit anything) resulting the following strange error.
Could the authors give some insights on the reasons?

> Plotting accuracy for dataset colour
> The following model(s) were not found: alexnet
> List of possible models in this dataset:
> ['bagnet33' 'resnet50' 'simclr_resnet50x1']
> The following model(s) were not found: subject-*
> List of possible models in this dataset:
> ['bagnet33' 'resnet50' 'simclr_resnet50x1']
> Traceback (most recent call last):
>   File "examples/evaluate.py", line 28, in <module>
>     run_plotting()
>   File "examples/evaluate.py", line 18, in run_plotting
>     figure_directory_name = figure_dirname)
>   File "/home/eric/model_vs_human/modelvshuman/plotting/plot.py", line 108, in plot
>     result_dir=result_dir)
>   File "/home/eric/model_vs_human/modelvshuman/plotting/plot.py", line 744, in plot_accuracy
>     result_dir=result_dir, plot_type="accuracy")
>   File "/home/eric/model_vs_human/modelvshuman/plotting/plot.py", line 772, in plot_general_analyses
>     experiment=e)
>   File "/home/eric/model_vs_human/modelvshuman/plotting/analyses.py", line 254, in get_result_df
>     r = self.analysis(subdat)
>   File "/home/eric/model_vs_human/modelvshuman/plotting/analyses.py", line 284, in analysis
>     self._check_dataframe(df)
>   File "/home/eric/model_vs_human/modelvshuman/plotting/analyses.py", line 24, in _check_dataframe
>     assert len(df) > 0, "empty dataframe"
> AssertionError: empty dataframe
>

**Comment by rgeirhos** [comment]
Hi @happyhackingit, thanks for reporting this, and sorry for the inconvenience.
This was caused by the fact that the code requested AlexNet plotting, but the evaluation code did not evaluate AlexNet (but instead bagnet33). It should work now (#a1aff4b)

**Comment by happyhackingit** [comment]
This is great, thanks @rgeirhos !
